version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-test
    command: nodemon start
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    links:
      - redis
    environment:
      REDIS_CONNECTION_STRING_URL: redis://default@redis:6379
      APP_NAME: crypto-ticker-api
      API_KEY: dummy
      NODE_ENV: development

  redis:
    image: redis
