FROM node:14

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY package*.json ./

ENV NR_NATIVE_METRICS_NO_DOWNLOAD true

RUN yarn global add node-gyp
RUN yarn install

# Bundle app source
COPY . .

CMD [ "yarn", "start:configs-worker" ]