FROM node:16

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package.json ./
COPY yarn.lock ./

RUN apt-get update
RUN yarn install --frozen-lockfile

# Bundle app source
COPY . .

HEALTHCHECK --interval=60s --timeout=2s --start-period=15s \  
    CMD node bin/healthcheck.js

CMD [ "yarn", "start" ]
